# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: running_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='running_message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15running_message.proto\x1a\x1bgoogle/protobuf/empty.proto\"^\n\x0eRunningDetails\x12\x10\n\x08\x64istance\x18\x01 \x01(\x02\x12\x0c\n\x04time\x18\x02 \x01(\x02\x12\x12\n\nheart_rate\x18\x03 \x01(\r\x12\x18\n\x10minutes_per_mile\x18\x04 \x01(\r\")\n\x16RunningMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"J\n\x0eRunningMetrics\x12\x12\n\nheart_rate\x18\x01 \x01(\r\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\x12\x12\n\ntime_stamp\x18\x03 \x01(\t2\xd5\x01\n\x0eRunningMessage\x12?\n\x11GetRunningMessage\x12\x0f.RunningDetails\x1a\x17.RunningMessageResponse\"\x00\x12@\n\x11LogRunningMetrics\x12\x0f.RunningMetrics\x1a\x16.google.protobuf.Empty\"\x00(\x01\x12@\n\x11GetRunningMetrics\x12\x16.google.protobuf.Empty\x1a\x0f.RunningMetrics\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_RUNNINGDETAILS = _descriptor.Descriptor(
  name='RunningDetails',
  full_name='RunningDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distance', full_name='RunningDetails.distance', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='RunningDetails.time', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heart_rate', full_name='RunningDetails.heart_rate', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minutes_per_mile', full_name='RunningDetails.minutes_per_mile', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=148,
)


_RUNNINGMESSAGERESPONSE = _descriptor.Descriptor(
  name='RunningMessageResponse',
  full_name='RunningMessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='RunningMessageResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=191,
)


_RUNNINGMETRICS = _descriptor.Descriptor(
  name='RunningMetrics',
  full_name='RunningMetrics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='heart_rate', full_name='RunningMetrics.heart_rate', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance', full_name='RunningMetrics.distance', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='RunningMetrics.time_stamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=267,
)

DESCRIPTOR.message_types_by_name['RunningDetails'] = _RUNNINGDETAILS
DESCRIPTOR.message_types_by_name['RunningMessageResponse'] = _RUNNINGMESSAGERESPONSE
DESCRIPTOR.message_types_by_name['RunningMetrics'] = _RUNNINGMETRICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RunningDetails = _reflection.GeneratedProtocolMessageType('RunningDetails', (_message.Message,), {
  'DESCRIPTOR' : _RUNNINGDETAILS,
  '__module__' : 'running_message_pb2'
  # @@protoc_insertion_point(class_scope:RunningDetails)
  })
_sym_db.RegisterMessage(RunningDetails)

RunningMessageResponse = _reflection.GeneratedProtocolMessageType('RunningMessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _RUNNINGMESSAGERESPONSE,
  '__module__' : 'running_message_pb2'
  # @@protoc_insertion_point(class_scope:RunningMessageResponse)
  })
_sym_db.RegisterMessage(RunningMessageResponse)

RunningMetrics = _reflection.GeneratedProtocolMessageType('RunningMetrics', (_message.Message,), {
  'DESCRIPTOR' : _RUNNINGMETRICS,
  '__module__' : 'running_message_pb2'
  # @@protoc_insertion_point(class_scope:RunningMetrics)
  })
_sym_db.RegisterMessage(RunningMetrics)



_RUNNINGMESSAGE = _descriptor.ServiceDescriptor(
  name='RunningMessage',
  full_name='RunningMessage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=270,
  serialized_end=483,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRunningMessage',
    full_name='RunningMessage.GetRunningMessage',
    index=0,
    containing_service=None,
    input_type=_RUNNINGDETAILS,
    output_type=_RUNNINGMESSAGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LogRunningMetrics',
    full_name='RunningMessage.LogRunningMetrics',
    index=1,
    containing_service=None,
    input_type=_RUNNINGMETRICS,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRunningMetrics',
    full_name='RunningMessage.GetRunningMetrics',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_RUNNINGMETRICS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RUNNINGMESSAGE)

DESCRIPTOR.services_by_name['RunningMessage'] = _RUNNINGMESSAGE

# @@protoc_insertion_point(module_scope)
